spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mariadb://localhost:3306/meu_banco
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never
server:
  port: 9997