app:
  myport: ${PORT:0}
server:
  port: ${app.myport}
spring:
  application:
    name: psicologo-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:psicologo
    username: admin
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


resilience4j:
  circuitbreaker:
    instances:
      avaliacaoService:
        register-health-indicator: true
        minimum-number-of-calls: 2
        sliding-window-size: 2
        wait-duration-in-open-state:
          seconds: 600

