server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/matheus-avvelino/conficserver
          clone-on-start: true
          search-paths:
            - "config"
          username: matheus-avvelino